spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/querydsl
    #url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #show_sql: true #system.out 출력
        format_sql: true #logger 출력

#  data:
#    web:
#      pageable:
#        default-page-size: 10
#        max-page-size: 2000

logging.level:
  org.hibernate.SQL: debug
  #org.hibernate.type: trace